name: HelloDock Smoke Test suite

on:
  schedule:
    - cron: "0 * * * *"  # Runs the tests every hour
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select The Environment URL
        options:
          - https://qa.hellodock.com/
          - https://dev.hellodock.com/
          - https://app.hellodock.com/

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm ci

     # - name: Install Playwright browsers
      #  run: npx playwright install

      - name: Install Playwright Allure
        run: npm install --save-dev allure-playwright

      # Run Playwright tests
      - name: Run Playwright tests
        env:
          BASE_URL: ${{ github.event.inputs.choice }}
        run: |
          npx playwright test --reporter=line,allure-playwright
        continue-on-error: true

      # Check if Playwright tests failed and set CC email based on that
      - name: Set CC Email for test failures
        if: failure()
        run: echo "CC_EMAIL=tqa8769@gmail.com" >> $GITHUB_ENV

      #- name: Set CC Email for success (No CC)
      #  if: success()
      #  run: echo "CC_EMAIL=" >> $GITHUB_ENV

      # Upload Playwright test results as artifacts
      - name: Upload Playwright test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/test-results/**'

      # Upload Allure results
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

      # Get Build URL for email
      - name: Get Build URL
        run: |
          echo "The Build URL is: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      # Send email notification with conditional CC based on test result
      - name: Send email notification
        if: always()  # Always send the email
        uses: dawidd6/action-send-mail@v3
        with:
          from: Hellodock Team <no-reply@hellodock.com>
          to: rahul.trello2020@gmail.com
          cc: ${{ env.CC_EMAIL }}  # Adds CC only if tests fail
          subject: Test Automation Build Job Status:${{ job.status }}
          body: |
            Hello Team,

            The build process for your smoke test is completed. Please use the link below to view the result.

            Build URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Environment: ${{ github.event.inputs.choice }}
            
            Thanks,
            HelloDock Automation Team
          server_address: email-smtp.us-east-2.amazonaws.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: false

  publish:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      - name: Print Allure Report URL
        run: |
            echo "Allure report is available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
