name: HelloDock Playwright Tests

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select The Environment URL
        options:
          - https://dev.hellodock.com/
          - https://qa.hellodock.com/
          - https://app.hellodock.com/

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ github.event.inputs.choice }}  # Pass the selected URL to the tests
        run: |
          npx playwright test --reporter=line,allure-playwright || true

      ## Install Allure and serve Allure Report via ngrok
      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Install ngrok
        run: npm install -g ngrok

      - name: Serve Allure Report and expose via ngrok
        shell: powershell
        run: |
          npx allure generate ./allure-results --clean -o ./allure-report
          Start-Process -FilePath "npx" -ArgumentList "allure", "serve", "./allure-results"
          Start-Process -FilePath "ngrok" -ArgumentList "http", "127.0.0.1:5252"
          Start-Sleep -Seconds 10  # Give ngrok more time to start
          $ngrokApiUrl = "http://127.0.0.1:4040/api/tunnels"
          try {
            $ngrokUrl = (Invoke-RestMethod -Uri $ngrokApiUrl).tunnels[0].public_url
            Write-Host "Allure Report is accessible at: $ngrokUrl"
            echo "::set-output name=allure_report_url::$ngrokUrl"
          }
          catch {
            Write-Host "Ngrok tunnel failed to start. Check ngrok logs."
            throw
          }

      # Upload the test results folder as an artifact
      - name: Upload Playwright test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/test-results/**'

      # Upload Allure results as an artifact (optional)
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/

      # Get Build URL
      - name: Get Build URL
        run: |
          echo "The Build URL is: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      # Send email notification with the Allure report link
      - name: Send email notification
        if: always()  # Ensures email is sent regardless of build success or failure
        uses: dawidd6/action-send-mail@v3
        with:
          from: Rahul <no-reply@hellodock.com>
          to: rahul.trello2020@gmail.com
          subject: Playwright Build Completed
          body: |
            Hello Rahul,

            The build process for your Playwright TypeScript project has completed. Please check the results.

            - Build URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Allure Report: ${{ steps.serve_allure.outputs.allure_report_url }}

            Thanks,
            HelloDock Automation Team
          server_address: email-smtp.us-east-2.amazonaws.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: false
