name: HelloDock Smoke Test suite

on:
  schedule:
     #- cron: "0 1 * * 1"
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select The Environment URL
        options:
          - https://app.hellodock.com/
          - https://qa.hellodock.com/
          - https://dev.hellodock.com/
          - https://httpstat.us/400
          - https://httpstat.us/500
          - https://httpstat.us/404
          - https://httpstat.us/200
          
        required: false
        
jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Validate selected environment URL
        shell: bash
        run: |
            echo "Checking if the environment URL is reachable..."
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" "${{ github.event.inputs.choice }}")
            echo "Status code: $STATUS_CODE"
            if [ "$STATUS_CODE" -ne 200 ]; then
              echo "Error: Selected environment URL returned status code $STATUS_CODE."
              exit 1
            fi
            echo "Environment URL is reachable."

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install Playwright Allure
        run: npm install --save-dev allure-playwright

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ github.event.inputs.choice }}
        run: |
          npx playwright test --reporter=line,allure-playwright
        continue-on-error: true
        id: playwright-tests

      - name: Set CC Email for test failures
        if: (steps.playwright-tests.outcome == 'failure')
        run: echo "CC_EMAIL=${{ vars.FAILURE_CC_EMAIL }}" >> $GITHUB_ENV
        shell: bash

      - name: Set CC Email for test successes
        if: (steps.playwright-tests.outcome == 'success')
        run: echo "CC_EMAIL=${{ vars.SUCCESS_CC_EMAIL }}" >> $GITHUB_ENV
        shell: bash

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/test-results/**'

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

      - name: Set and print BASE_URL
        run: |
            # Set BASE_URLp to the input choice or fallback to the default if it's empty
            BASE_URLp="${{ github.event.inputs.choice || 'https://app.hellodock.com/' }}"
            echo "BASE_URLp=$BASE_URLp" >> $GITHUB_ENV
        shell: bash

      - name: Send email notification
        if: always()  # Always send the email
        env:
          CC_EMAIL: ${{ env.CC_EMAIL }}  # Use the CC_EMAIL variable set in previous steps
        uses: dawidd6/action-send-mail@v3
        with:
          from: Hellodock Team <no-reply@hellodock.com>
          to: rahul.trello2020@gmail.com
          cc: ${{ env.CC_EMAIL }}  # CC set based on success or failure
          subject: 'Test Automation Build Job Status: ${{ job.status }}'
          body: |
            Hello Team,

            The build process for your smoke test is completed. Please use the link below to view the result.

            Build URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Allure Report: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_id }}/
            Environment: ${{ env.BASE_URLp }} 
            
            Thanks,
            HelloDock Automation Team
          server_address: email-smtp.us-east-2.amazonaws.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: false

  publish:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report

      # Ensure the previous history is retained on GitHub Pages
      - name: Deploy to GitHub Pages with unique folder per build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: "${{ github.run_id }}"  # Use run ID to create a unique folder per build
          

      - name: Print Allure Report URL
        run: |
            echo "Allure report is available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_id }}/"
