name: HelloDock PlaywrightTestings

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select The Environment URL
        options:
          - https://dev.hellodock.com/
          - https://qa.hellodock.com/
          - https://app.hellodock.com/
        required: true

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Downgrade to Node.js 18 for compatibility

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Download the previous Allure history if available
      - name: Download Previous Allure History
        uses: actions/download-artifact@v3
        with:
          name: allure-history
          path: allure-results/history
        continue-on-error: true

      # Step 5: Run Playwright tests
      - name: Run Playwright Tests
        run: npm run test || true  # `|| true` ensures the pipeline does not fail even if tests fail
        env:
          CI: true
          ENV_URL: ${{ github.event.inputs.choice }}  # Pass the selected environment URL

      # Step 6: Generate Allure Report with History (Windows)
      - name: Generate Allure Report with History
        shell: pwsh  # Use PowerShell on Windows
        run: |
          if (Test-Path -Path "allure-results/history") {
            echo "Previous Allure history found."
          } else {
            echo "No previous history found, creating a new history folder."
            New-Item -ItemType Directory -Path "allure-results/history"
          }
          npm run allure:generate

      # Step 7: Upload the new Allure results
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # Step 8: Upload Allure history for the next build
      - name: Upload Allure History
        uses: actions/upload-artifact@v3
        with:
          name: allure-history
          path: allure-results/history

      # Step 9: Publish Allure report to GitHub Pages (keeps report history)
      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true  # Keep history of previous reports
