name: HelloDock Smoke Test suite Old

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select The Environment URL
        options:
          - https://qa.hellodock.com/
          - https://dev.hellodock.com/
          - https://app.hellodock.com/

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm ci

     # - name: Install Playwright browsers
     #   run: npx playwright install

      - name: Install Playwright Allure
        run: npm install --save-dev allure-playwright

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ github.event.inputs.choice }}
        run: |
          npx playwright test --reporter=line,allure-playwright || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      ## Upload the Playwright test results to S3
      - name: Upload Playwright test results to S3
        run: |
          aws s3 cp --recursive ./test-results s3://your-s3-bucket-name/test-results/${{ github.run_id }}/

      ## Upload the Allure results to S3
      - name: Upload Allure Results to S3
        run: |
          aws s3 cp --recursive ./allure-results s3://your-s3-bucket-name/allure-results/${{ github.run_id }}/

      - name: Get Build URL
        run: |
          echo "The Build URL is: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      ## Send email notification with Allure link
      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          from: Hellodock Team <no-reply@hellodock.com>
          to: rahul.trello2020@gmail.com
          subject: Test Automation Build Job Status:${{ job.status }}
          body: |
            Hello Team,

            The build process for your smoke test is completed. Please use below URLs to view results:

            Playwright Test Results: https://your-s3-bucket-name.s3.amazonaws.com/test-results/${{ github.run_id }}/index.html
            Allure Report: https://your-s3-bucket-name.s3.amazonaws.com/allure-results/${{ github.run_id }}/index.html
            Environment: ${{ github.event.inputs.choice }}
           
            Thanks,
            HelloDock Automation Team
          server_address: email-smtp.us-east-2.amazonaws.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: false

  publish:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure Results from S3
        run: |
          aws s3 cp --recursive s3://your-s3-bucket-name/allure-results/${{ github.run_id }}/ ./allure-results/

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report

      - name: Upload Allure Report to S3
        run: |
          aws s3 cp --recursive ./allure-report s3://your-s3-bucket-name/allure-reports/${{ github.run_id }}/
      
      - name: Print Allure Report URL
        run: |
          echo "Allure report is available at: https://your-s3-bucket-name.s3.amazonaws.com/allure-reports/${{ github.run_id }}/index.html"
