name: HelloDock Playwright Tests

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select The Environment URL
        options:
          - https://dev.hellodock.com/
          - https://qa.hellodock.com/
          - https://app.hellodock.com/

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Downgrade to Node.js 18 for compatibility

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm ci

      # Step 4: Download the previous Allure history if available
      - name: Download Previous Allure History
        uses: actions/download-artifact@v3
        with:
          name: allure-history
          path: allure-results/history
        continue-on-error: true

      # Step 5: Run Playwright tests
      - name: Run Playwright Tests
        run: npm run test
        env:
          CI: true

      # Step 6: Generate Allure report with history
      - name: Generate Allure Report with History
        run: |
          if [ -d "allure-results/history" ]; then
            echo "Previous Allure history found."
          else
            echo "No previous history found, creating a new history folder."
            mkdir -p allure-results/history
          fi
          npm run allure:generate

      # Step 7: Upload the new Allure results
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # Step 8: Upload Allure history for the next build
      - name: Upload Allure History
        uses: actions/upload-artifact@v3
        with:
          name: allure-history
          path: allure-results/history

      # Step 9: Publish Allure report to GitHub Pages (keeps report history)
      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          # Keep history of previous reports
          keep_files: true

