name: TestsAllureReportHYSTORY

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select The Environment URL
        options:
          - https://dev.hellodock.com/
          - https://qa.hellodock.com/
          - https://app.hellodock.com/

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Allure
        run: npm install --save-dev allure-playwright

      - name: Run Playwright Tests
        run: npx playwright test --reporter=line,allure-playwright || true

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

  publish:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download previous report history
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          if (Test-Path allure-results/history) {
            Remove-Item -Recurse -Force allure-results/history
          }
          if (Test-Path gh-pages/history) {
            Copy-Item -Recurse gh-pages/history allure-results/
          }

      - name: Download Allure Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
          allure --version

      - name: Generate Allure Report with History
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Clean old gh-pages content
        run: |
          Remove-Item -Recurse -Force ./gh-pages  # Updated for Windows

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          force_orphan: true
